### ISSUE TITLE
Error while following integration

### ISSUE THREAD

**Issue by tyler-whitman** [flybayer/blitz-sentry#2]
Hello, trying to follow this integration with a blitz app. After adding all the code in the files mentioned I end up getting the following error:

```
Error: A React component suspended while rendering, but no fallback UI was specified.
Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    at renderToStringImpl (/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6450:11)
    at renderToString (/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6457:10)
    at Object.renderPage (/node_modules/next/dist/server/render.js:653:31)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:193:19)
    at Object.loadGetInitialProps (/node_modules/next/dist/shared/lib/utils.js:69:29)
    at Object.renderToHTML (/node_modules/next/dist/server/render.js:676:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async doRender (/node_modules/next/dist/server/next-server.js:1133:38)
    at async /node_modules/next/dist/server/next-server.js:1227:28
```

dependencies:
```
    "@sentry/browser": "7.11.1",
    "@sentry/integrations": "7.11.1",
    "@sentry/node": "7.11.1",
    "@sentry/webpack-plugin": "1.19.0",
    "blitz": "0.45.3",
```

I do have a `<Suspense />` component in my `_app.tsx` file right below the `<ErrorBoundary />` in the tree. Any ideas? Does this still work?

**Comment by flybayer** [comment]
Do you have a `fallback` prop on `<Suspense />`?

Either way, not sure why you hit this when adding sentry, should be totally separate.

**Comment by tyler-whitman** [comment]
Yes I do, I updated react-dom and I see a new message at that spot in the code:

```
    // Note: This error message is the one we use on the client. It doesn't
    // really make sense here. But this is the legacy server renderer, anyway.
    // We're going to delete it soon.
    throw new Error('A component suspended while responding to synchronous input. This ' + 'will cause the UI to be replaced with a loading indicator. To fix, ' + 'updates that suspend should be wrapped with startTransition.');
```

I'm not sure what is causing this suspense to happen, but if I comment out that error everything loads fine. Maybe I'll just patch it for now, but it only happens when I bring in the sentry integration.

my react / react-dom versions btw:
```
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

**Comment by tyler-whitman** [comment]
Another question, do you know with blitz 2.0 if we can use the standard next.js sentry integration? Maybe I'll try that?

**Comment by tyler-whitman** [comment]
Gave Blitz 2 a shot and it looks like it works without errors now. I just used the standard next.js sentry integration, so I think I will go with the Blitz 2 upgrade. Thank you for the reply.
